version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: anyam22/lslab3-client:v1

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: anyam22/lslab3-server:v1