# NOTE: This file should not be committed to a repository 
#       as it contains critical data.
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
stringData:
  mongo-url: "mongodb://mongo-srv/iu"